dialect: mysql
tables:
  orders:
    mask_columns:
    - shipping_address: address
    - order_date: date
    primary_key: id
  users:
    mask_columns:
    - email: email
    - phone: phone
    - password: password
    - address: address
    primary_key: id
