batch_size: 10
tables:
    users:
      primary_key: id
      shuffle:
        - email: email
        - phone: phone
        - password: password
        - address: address
    orders:
      primary_key: id 
      shuffle:
        - shipping_address: address
        - order_date: date