dialect: mysql # could be postgres
tables:
    users:
      primary_key: id
      mask_columns:
        - email: email
        - phone: phone
        - password: password
        - address: address
    orders:
      primary_key: id 
      mask_columns:
        - shipping_address: address
        - order_date: date


# More info
# mask_columns:
#   column_name: mask_type

# mask_types:
#   email
#   phone
#   password
#   address
#   date

